#!/bin/sh
set -eu

# bind mount sources must exist before the container is created.
mkdir -p "$HOME/.codex" "$HOME/.config/gemini" "$HOME/.claude"

if [ -d "$HOME/.claude.json" ]; then
  echo "error: $HOME/.claude.json must be a file, but is a directory" >&2
  exit 1
fi

# Claude Code treats a zero-byte file as corrupted.
[ -s "$HOME/.claude.json" ] || printf '{}\n' >"$HOME/.claude.json"

version_dir="$HOME/.cache/devcontainer-ai-cli"
version_file="$version_dir/versions.env"
version_tmp="$version_dir/versions.env.tmp.$$"
mkdir -p "$version_dir"
trap 'rm -f "$version_tmp"' EXIT HUP INT TERM

detect_version() {
  command_name="$1"

  command -v "$command_name" >/dev/null 2>&1 || return 0
  "$command_name" --version 2>/dev/null \
    | sed -nE 's/^[^0-9]*([0-9]+\.[0-9]+\.[0-9]+([-+][0-9A-Za-z.-]+)?).*$/\1/p' \
    | sed -n '1p'
}

write_version() {
  variable_name="$1"
  command_name="$2"
  detected_version="$(detect_version "$command_name")"

  if [ -n "$detected_version" ]; then
    printf '%s=%s\n' "$variable_name" "$detected_version" >>"$version_tmp"
  fi
}

{
  printf '# Generated by .devcontainer/initialize-host.sh; contains no credentials.\n'
} >"$version_tmp"

write_version CODEX_CLI_VERSION codex
write_version CLAUDE_CODE_VERSION claude
write_version GEMINI_CLI_VERSION gemini

mv "$version_tmp" "$version_file"
trap - EXIT HUP INT TERM

detected="$(sed -n '2,$p' "$version_file" | tr '\n' ' ')"
if [ -n "$detected" ]; then
  printf 'devcontainer: detected host AI CLI versions: %s\n' "$detected"
else
  printf 'devcontainer: no supported AI CLI found on the host; image versions will be used\n'
fi
